
["Energy Settings"]
	#Maximum energy capacity of the Multibuilder Tool (in FE)
	#Range: 100000 ~ 100000000
	maxEnergy = 10000000
	#Energy transfer rate for charging/discharging (in FE/tick)
	#Range: 10000 ~ 1000000
	energyTransferRate = 100000
	#Energy cost per block placed (in FE)
	#Range: 1 ~ 10000
	energyPerBlock = 100

