
#Client Settings
[Client]

	[Client.Notifications]
		#Set to true to play a sound when a mercenary's mission is complete.
		playMissionFinishedSound = true
		#Set to true to show a chat message when a mercenary's mission is complete.
		showMissionFinishedMessage = true

		[Client.Notifications.Arena]
			#Set to true to show the teams health bar in the Arena.
			showArenaTeamsHud = true
			#Set the scale of the teams HUD in the Arena.
			#Range: 0.1 ~ 3.0
			arenaTeamsHudScale = 0.75

		[Client.Notifications.Sounds]
			#Set to true to mute all sounds from this mod.
			muteAllSounds = false
			#Set to true to allow mercenaries to play voice lines for certain events.
			playMercenaryVoicelines = true
			#Set to true to show a chat message transcript of mercenary voice lines.
			showMercenaryVoicelineTranscripts = false

